:no title:

The Jetty projects was started in 1995 and since then has been associated with many names and brands:

== Distributions

=== Jetty 
The Jetty Web Server provides an HTTP server and Servlet container capable of serving static and dynamic content either from a standalone or embedded instantiations. 
From jetty-7 on, the jetty web-server and other core components are hosted by the Eclipse Foundation. 
The project provides:

* Asynchronous HTTP Server
* Standards based Servlet Container
* Web Sockets server
* SPDY server
* Asynchronous HTTP Client
* OSGI, JNDI, JMX, JASPI, AJP support 

=== Hightide 
A note about Jetty Hightide. Previous releases of Jetty (6, 7 and 8) each released an additional distribution that contained some 3rd party integrations to give a more JEE experience however with Jetty 9 we have stopped providing this integration. 
What we have found is the vast majority of our users simply start with the jetty-distribution and then layer in whatever extra technologies they want to use, either into the distribution itself or within their web applications. 
Technologies like JNDI, JMX, and Annotations have always existed in the stock jetty-distribution to weave such things together and that will remain the case.

=== Other 

Previous releases of Jetty have been available in many forms and distributions, including the jetty-maven-plugin (which is now hosted at eclipse), Debian and RPMs from jetty@codehaus and as part of the Geronimo JEE application server from apache.


== Homes

The Jetty project has found its home in many places over the last 20+ years.

=== Eclipse
In 2009, the Jetty project moved its core components to be a project of the Eclipse Foundation, in order to improve the IP processes and broaden the licensing and community of the project. As of Jetty 9 the project has fully moved to the Eclipse Foundation.

=== Codehaus
In 2005, the jetty project moved to the The Codehaus for its hosting services and open source community. In 2009, after the core components of Jetty moved to eclipse, the jetty @ codehaus project continues to provide integrations, extensions and packaging of jetty.

=== Sourceforge
From 2000 to 2005, the jetty project was hosted at sourceforge.net where versions 3.x, 4.x and 5.x were produced.


== Sponsors

The development of the Jetty project has been fully funded over the years through close collaboration with a great many of wonderful clients.  We have done with work through a number of entities as mentioned here.

=== Webtide
In 2015 the development of Jetty was once more taken over by Webtide when the developers split away from Intalio, taking over full ownership of the company behind the open source project. Webtide now fully funds the ongoing development of the Jetty project through services and support on the open source version of the Jetty project.

=== Intalio
The role of the development of Jetty was taken over in 2009 by Webtide LLC, who acquired both Webtide and Mort Bay. Intalio is a company that offers both products and services based on open source software and they employ many of the jetty contributors.

=== Webtide
The role of leading the development of Jetty was taken over in 2006 by Webtide LLC, formed as a joint venture between Mort Bay and partners providing marketing, sales and strategic assistance.

=== Mort Bay
The Java HTTP server that became jetty was originally developed in 1995 by Greg Wilkins of Mort Bay Consulting as part of an issue tracking application. Versions 1.x through to 6.1.x of jetty were developed under org.mortbay packaging and Mort Bay still holds the major part of the copyright on the jetty code base. Mort Bay directly hosted the jetty project until version 3.x and was the prime sponsor of development until 6.x.


== Versions

[caption=]
.Jetty Versions
[width="100%",cols="12%,9%,15%,6%,21%,10%,6%,21%",options="header",]
|=======================================================================
|Version |Year |Home |JVM |Protocols |Servlet |JSP |Status
|9.3 |2015 |Eclipse |1.8 |HTTP/1.1 (RFC 7230), HTTP/2 (RFC 7540), WebSocket (RFC 6455, JSR 356), FastCGI |3.1 |2.3 |Stable
|9.2 |2014 |Eclipse |1.7 |HTTP/1.1 RFC2616, javax.websocket, SPDY v3 |3.1 |2.3 |Stable
|8 |2009- |Eclipse/Codehaus |1.6 |HTTP/1.1 RFC2616, WebSocket RFC 6455, SPDY v3 |3.0 |2.2 |Venerable
|7 |2008- |Eclipse/Codehaus |1.5 |HTTP/1.1 RFC2616, WebSocket RFC 6455, SPDY v3 |2.5 |2.1 |Venerable
|6 |2006-2010 |Codehaus |1.4-1.5 |HTTP/1.1 RFC2616 |2.5 |2.0 |Deprecated
|5 |2003-2009 |Sourceforge |1.2-1.5 |HTTP/1.1 RFC2616 |2.4 |2.0 |Deprecated
|4 |2001-2006 |Sourceforge |1.2, J2ME |HTTP/1.1 RFC2616 |2.3 |1.2 |Ancient
|3 |1999-2002 |Sourceforge |1.2 |HTTP/1.1 RFC2068 |2.2 |1.1 |Fossilized
|2 |1998-2000 |Mortbay |1.1 |HTTP/1.0 RFC1945 |2.1 |1.0 |Legendary
|1 |1995-1998 |Mortbay |1.0 |HTTP/1.0 RFC1945 |- |- |Mythical
|=======================================================================
