[[eclipse-jetty-download]]

== Eclipse Jetty Downloads

The latest release of Eclipse Jetty is below, earlier minor release versions are available in https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution[Maven Central.]


.empty
[width="100%",cols="30%,10%,10%,10%,10%",options="header",]
|=======================================================================
| Release | | | |
| 9.4.26.v20200117
| https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.26.v20200117/jetty-distribution-9.4.26.v20200117.zip[.zip]
| https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.26.v20200117/jetty-distribution-9.4.26.v20200117.tar.gz[.tgz]
| http://www.eclipse.org/jetty/javadoc/9.4.26.v20200117/index.html?overview-summary.html[apidocs]
| https://github.com/eclipse/jetty.project/tree/jetty-9.4.26.v20200117[source]
|=======================================================================


*Note:* Release notes can be found in the `VERSION.txt` file included with the distribution and on the link:https://github.com/eclipse/jetty.project/releases[GitHub Releases] page for the Jetty project.
Release notes are also made available on the link:https://www.eclipse.org/jetty/mailinglists.html[jetty-announce@eclipse.org mailing list.]

=== Prior Versions
The most recent versions of prior Jetty releases can be found link:previousversions.html[here, with their associated documentation.]

Note: The canonical repository for Jetty is Maven Central.  All releases are always available there first and this download page may lag a bit update wise as post release resources are put into place.  You can always browse for Jetty releases https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution[here].

=== Jetty P2 Provisioning

This provisioning address is not for general use and are provided strictly for OSGI users.

* Composite Jetty 9 P2 Provisioning: \http://download.eclipse.org/jetty/updates/jetty-bundles-9.x
